### ISSUE TITLE
switch blueprint to global field definition

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-hero-field#4]
if you switch the field definition to a global field definition you could avoid the empty string label, right?

**Comment by jenstornell** [comment]
Yes, I could but I don't know why I left it empty in the first place. Often a label is good for fields like this. I've added a label now in the readme so that it does not look weird.

I'm not sure about the field definition in this case. We can remove the label from the blueprint and just keep the type if we want. Also, should every field have a global field definition? I'm not sure and I'm closing it for the moment.
